spring:
  application:
    name: swap-books
  config:
    import: "optional:file:.env[.properties]"
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: swap-books
  logging:
    level:
      org.springframework.boot.context.config: DEBUG